/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.idahodata.app;

// import io.idahodata.list.LinkedList;
//
// import static io.idahodata.utilities.StringUtils.join;
// import static io.idahodata.utilities.StringUtils.split;
// import static io.idahodata.app.MessageUtils.getMessage;

import io.idahodata.stanley.anotation.EnableStanley;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.text.WordUtils;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import java.util.Scanner;

@Slf4j
@SpringBootApplication
@EnableStanley
public class App implements CommandLineRunner {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }


    @Override
    public void run(String... args) {
        log.info("Press <ENTER> to exit");
        Scanner scanner = new Scanner(System.in);
        scanner.nextLine();
    }
}
