/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.idahodata.java-application-conventions")
    id("io.idahodata.stanley-conventions")
    id("org.springframework.boot") version "3.0.6"
    id("io.spring.dependency-management") version "1.1.0"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":stanley"))
}

application {
    // Define the main class for the application.
    mainClass.set("io.idahodata.app.App")
}
