spring:
  kafka:
    bootstrap-servers: localhost:29092

  cloud:
    stream:
      function:
        definition: news-consumer
        bindings:
          news-consumer-in-0: news-consumer-sub

      default-binder: kafka-1

      bindings:
        news-consumer-sub:
          destination: news-stories
          content-type: application/*+avro

      binders:
        kafka-1:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder:
              brokers: localhost:29092
              consumer-properties:
                schema.registry.url: http://localhost:28081
                key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                spring.deserializer.key.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
                value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
                spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer



